version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/.github/workflows"
    schedule:
      interval: weekly
      day: wednesday
      time: "05:00"
      timezone: "UTC"
    groups:
      gha-all:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/templates/actions/workflows"
    schedule:
      interval: weekly
      day: wednesday
      time: "05:00"
      timezone: "UTC"
    groups:
      gha-all:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/templates/dockerized/workflows"
    schedule:
      interval: weekly
      day: wednesday
      time: "05:00"
      timezone: "UTC"
    groups:
      gha-all:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/templates/other/workflows"
    schedule:
      interval: weekly
      day: wednesday
      time: "05:00"
      timezone: "UTC"
    groups:
      gha-all:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/templates/static/workflows"
    schedule:
      interval: weekly
      day: wednesday
      time: "05:00"
      timezone: "UTC"
    groups:
      gha-all:
        patterns:
          - "*"
