version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/templates/actions/workflows"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/templates/dockerized/workflows"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/templates/other/workflows"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/templates/static/workflows"
    schedule:
      interval: "daily"
