name: (Cron) Check dependencies

on:
  schedule:
    # Run every Monday at 08:00 UTC
    - cron: 0 8 * * 1

permissions:
  contents: read
  packages: write

jobs:
  call-dependency-check:
    uses: devops-infra/.github/.github/workflows/reusable/cron-check-dependencies.yml@master
    with:
      runs-on: ubuntu-24.04-arm
      task-version: 3.x
      docker-platforms: amd64,arm64
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
