name: (Auto) Create Pull Request

on:
  workflow_call:
    inputs:
      runs-on:
        description: Runner to use
        type: string
        default: ubuntu-24.04-arm
      task-version:
        description: Task version to install
        type: string
        default: 3.x

jobs:
  call:
    uses: devops-infra/.github/templates/actions/workflows/auto-create-pull-request.yml@v1
    with:
      runs-on: ${{ inputs.runs-on }}
      task-version: ${{ inputs.task-version }}
      enable-docker: false
      enable-lint: true
