name: (Manual) Update Version

on:
  workflow_dispatch:
    inputs:
      type:
        description: Bump type
        required: false
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
          - set
      version:
        description: Explicit version when type="set" (e.g., v1.2.3)
        required: false
        default: ''

permissions:
  contents: write

jobs:
  call:
    uses: devops-infra/.github/.github/workflows/reusable-manual-update-version.yml@v1
    with:
      bump-type: ${{ inputs.type }}
      explicit-version: ${{ inputs.version }}
      profile: static
