name: (Auto) Pull Request Create

on:
  push:
    branches-ignore:
      - master
      - main
      - dependabot/**

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  call-auto-pull-request-create:
    uses: ./.github/workflows/reusable-auto-pull-request-create.yml
    with:
      runs-on: ubuntu-24.04-arm
      task-version: 3.x
      profile: other
    secrets: inherit
