name: (Auto) Create release

on: []

permissions:
  contents: write
  packages: write

jobs:
  call-auto-create-release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    uses: ./.github/workflows/reusable/auto-create-release.yml
    with:
      runs-on: ubuntu-24.04-arm
      task-version: 3.x
      docker-platforms: amd64,arm64
      version-suffix: ''
      update-dockerhub-description: true
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
