name: (Manual) Sync Common Files

on:
  workflow_dispatch:
    inputs:
      profile:
        description: Template profile to sync
        required: true
        default: other
        type: choice
        options:
          - actions
          - dockerized
          - other
          - static
      type:
        description: File type to sync
        required: true
        default: all
        type: choice
        options:
          - all
          - configs
          - ignores
          - taskfiles

permissions:
  contents: write
  pull-requests: write

jobs:
  call-sync-files:
    uses: ./.github/workflows/reusable-other-manual-sync-common-files.yml
    with:
      runs-on: ubuntu-24.04-arm
      task-version: 3.x
      sync-type: ${{ github.event.inputs.type }}
      template-profile: ${{ github.event.inputs.profile }}
