name: (Manual) Update Version

on:
  workflow_dispatch:
    inputs:
      type:
        description: Bump type
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
          - set
      version:
        description: Explicit version when type="set" (e.g., v1.2.3)
        required: false
        default: ''

permissions:
  contents: write
  pull-requests: write

jobs:
  call-version-update:
    uses: devops-infra/.github/templates/other/workflows/manual-update-version.yml@master
    with:
      runs-on: ubuntu-24.04-arm
      task-version: 3.x
      bump-type: ${{ github.event.inputs.type }}
      explicit-version: ${{ github.event.inputs.version }}
