name: (Reusable Other) Manual Sync Common Files

on:
  workflow_call:
    inputs:
      runs-on:
        description: Runner to use
        type: string
        default: ubuntu-24.04-arm
      task-version:
        description: Task version to install
        type: string
        default: 3.x
      sync-type:
        description: File type to sync (all, configs, ignores, taskfiles)
        type: string
        required: true
      template-profile:
        description: Template profile to use for Taskfile sync (actions, dockerized, other, static)
        type: string
        default: other

jobs:
  call:
    uses: ./.github/workflows/reusable-actions-manual-sync-common-files.yml
    with:
      runs-on: ${{ inputs.runs-on }}
      task-version: ${{ inputs.task-version }}
      sync-type: ${{ inputs.sync-type }}
      template-profile: ${{ inputs.template-profile }}
